import "./globals.css";
import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import Provider from "./(Providers)/NextUiProvider";
import { Toaster } from "react-hot-toast";
import { AuthProvider } from '../context/auth'
import { LoadingProvider, useLoading } from '../context/Loading'
import Loader from "@/components/loader/Loader";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

const monserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "IGNITION",
  description: "Generated by create next app",
};
// const [loading, setLoading] = useLoading();

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {


  return (
    <html lang="en">
      <body className={`${inter.variable} ${monserrat.variable}`}>
        <AuthProvider>
            <LoadingProvider>
              <Provider>
                <Toaster position="top-center" reverseOrder={false} />
                {children}
              </Provider>
            </LoadingProvider>
        </AuthProvider>
      </body>
    </html >
  );
}
